Step 1. Context, Constructor update
lomonosov9/react-burger pull request #3
Opened 2023-02-15 14:05 UTC by lomonosov9

2023-02-15 15:08 UTC, andryxxa93 requested changes
Хорошая работа!
Что понравилось:
- Правильно используется `useMemo`
- Есть проверка успешности запроса
- Правильно использовали `useReducer`
- Нет лишнего кода

Что необходимо исправить:
- В `BurgerIngredients` необходимо передавать ингредиенты через контекст, а не через пропсы.


Удачных правок!

2023-02-15 15:08 UTC, andryxxa93 commented on src/components/app/app.jsx
>                <BurgerIngredients data={data}></BurgerIngredients>
**Необходимо исправить**
На данном этапе необходимо передавать ингредиенты не через пропсы а через контекст.

2023-02-15 15:08 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  switch (action.type) {
**Можно лучше**
Здорово, что вы использовали `useReducer` для подсчета стоимости. Так же вы можете попробовать добавить пару экшенов для добавления/удаления в конструктор ингредиентов.

2023-02-16 08:21 UTC, lomonosov9 commented on src/components/burger-constructor/burger-constructor.jsx
> +  switch (action.type) {
эх, вот этот пункт не поняла что имелось ввиду. Но в будущем думаю это и так надо будет сделать по ТЗ.

2023-02-16 08:53 UTC, andryxxa93 approved these changes
Да, отлично! Теперь всё как надо. Работа принята, удачи в дальнейшем обучении!

2023-02-16 08:53 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +/*import ingredientType from '../../utils/prop-types';
**Можно улучшить**
Ненужный код лучше удалять

2023-02-16 08:53 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                <BurgerIngredients></BurgerIngredients>
**Можно лучше**
Когда не передается `children` можно использовать самозакрывающийся тег `<BurgerIngredients />`

2023-02-16 08:53 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +/*import ingredientType from '../../utils/prop-types';
```jsx
const constructorReducer = (state, action) => {
  switch (action.type) {
    case "ADD":
      if (action.payload.type === "bun") {
        return {
          ...state,
          bun: action.payload,
        };
      }
      return {
        ...state,
        ingredients: [action.payload, ...state.ingredients],
      };
    case "DELETE":
      return {
        ...state,
        ingredients: [
          ...state.ingredients.slice(0, action.payload),
          ...state.ingredients.slice(action.payload + 1),
        ],
      };
    case "RESET":
      return constructorInitialState;
    default:
      return state;
  }
};
```

2023-02-16 08:54 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  switch (action.type) {
Это можно было сделать примерно вот так. 
```jsx
const constructorReducer = (state, action) => {
  switch (action.type) {
    case "ADD":
      if (action.payload.type === "bun") {
        return {
          ...state,
          bun: action.payload,
        };
      }
      return {
        ...state,
        ingredients: [action.payload, ...state.ingredients],
      };
    case "DELETE":
      return {
        ...state,
        ingredients: [
          ...state.ingredients.slice(0, action.payload),
          ...state.ingredients.slice(action.payload + 1),
        ],
      };
    case "RESET":
      return constructorInitialState;
    default:
      return state;
  }
};
```

2023-02-16 09:18 UTC, merged